services:
  - type: web
    name: service-command-center-prototype
    env: node
    plan: free
    buildCommand: ""
    startCommand: "node server.mjs"
    envVars:
      - key: NODE_ENV
        value: production
